#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\MainController::index

about:
  path: /about
  controller: App\Controller\MainController::about

contact:
  path: /contact
  controller: App\Controller\MainController::contact

forum:
  path: /forum
  controller: App\Controller\MainController::categories

library:
  path: /library
  controller: App\Controller\MainController::library

notFound:
  path: /{slug}
  controller: App\Controller\MainController:notFound
