#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\MainController::index

about:
  path: /about
  controller: App\Controller\MainController::about

contact:
  path: /contact
  controller: App\Controller\MainController::contact

forum:
  path: /forum
  controller: App\Controller\MainController::categories

library:
  path: /library
  controller: App\Controller\MainController::library

login:
  path: /login
  controller: App\Controller\MainController::showlogin

register:
  path: /register
  controller: App\Controller\MainController::showregister

logout:
  path: /logout
  controller: App\Controller\MainController::logout

edit:
  path: /edit
  controller: App\Controller\MainController::edit_profile

add:
  path: /add
  controller: App\Controller\MainController::show_add

user_page:
  path: /user/{slug}
  controller: App\Controller\MainController::user_page

work_page:
  path: /work/{slug}
  controller: App\Controller\MainController::show_work

edit_work_details:
  path: /work/{slug}/edit
  controller: App\Controller\MainController::edit_work

notFound:
  path: /{slug}
  controller: App\Controller\MainController::not_found
